### ISSUE TITLE
gpt2-large seem to be supported but doesn't work in practice.

### ISSUE THREAD

**Issue by dimeldo** [bme-chatbots/dialogue-generation#11]
Is it just not ready yet or is this a bug?

```
Model name 'gpt2-large' was not found in model name list (gpt2-medium, gpt2). We assumed 'gpt2-large' was a path or url but couldn't find tokenizer filesat this path or url.
Traceback (most recent call last):
  File "run.py", line 92, in <module>
    main()
  File "run.py", line 69, in main
    _, tokenizer = create_dataset(args=args)
  File "/Downloads/dialogue-generation/src/data.py", line 533, in create_dataset
    tokenizer = create_tokenizer(args)
  File "/Downloads/dialogue-generation/src/data.py", line 505, in create_tokenizer
    instance.add_special_tokens({
AttributeError: 'NoneType' object has no attribute 'add_special_tokens'

```

**Comment by Mrpatekful** [comment]
You might not have the latest pytorch-transformers version. I recommend reinstalling it with `pip install git+https://github.com/huggingface/pytorch-transformers`. This should solve the problem.

**Comment by dimeldo** [comment]
Working 👍 Thanks.
