### ISSUE TITLE
Error adding special tokens to GPT2 tokenizer

### ISSUE THREAD

**Issue by dimeldo** [bme-chatbots/dialogue-generation#2]
Using GPT2 model and running your script with default settings get me the error below, which is probably related to the issue discussed here: https://github.com/huggingface/pytorch-transformers/issues/799

Can you help solve this, please?

```
Using unk_token, but it is not set yet.
Using unk_token, but it is not set yet.
Using unk_token, but it is not set yet.
Using unk_token, but it is not set yet.
Using unk_token, but it is not set yet.
Traceback (most recent call last):
  File "./src/train.py", line 515, in <module>
    main()
  File "./src/train.py", line 257, in main
    args=args, device=device)
  File "/Downloads/GPT2/src/data.py", line 525, in create_dataset
    tokenizer = create_tokenizer(args)
  File "/Downloads/GPT2/src/data.py", line 498, in create_tokenizer
    'additional_special_tokens': special_tokens})
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/tokenization_utils.py", line 335, in add_special_tokens
    added_special_tokens = self.add_tokens(special_tokens_dict.values())
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/tokenization_utils.py", line 311, in add_tokens
    if self.convert_tokens_to_ids(token) == self.convert_tokens_to_ids(self.unk_token):
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/tokenization_utils.py", line 381, in convert_tokens_to_ids
    for token in tokens:
TypeError: 'NoneType' object is not iterable
```

**Comment by Mrpatekful** [comment]
It seems like the issue has been fixed in pytorch-transformer master branch, but their pypi package is not yet up to date.
```
pip uninstall pytorch-transformers
pip install git+https://github.com/huggingface/pytorch-transformers
```
This will remove the old version and install the fix from git. I will be looking into removing requirements.txt and move all required dependencies to setup.py.

**Comment by dimeldo** [comment]
Thanks!
