### ISSUE TITLE
training error in python 3.7

### ISSUE THREAD

**Issue by pythonmobile** [bme-chatbots/dialogue-generation#22]
```
epoch    train_loss    train_acc    train_ppl    valid_loss    valid_acc    valid_ppl
-------  ------------  -----------  -----------  ------------  -----------  -----------
Traceback (most recent call last):                                                                                                                         
  File "/home/uname/.pyenv/versions/3.7.6/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/uname/.pyenv/versions/3.7.6/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/uname/proj/github/dialogue-generation/src/train.py", line 830, in <module>
    main()
  File "/home/uname/proj/github/dialogue-generation/src/train.py", line 760, in main
    for values in valid_metrics
ValueError: not enough values to unpack (expected 3, got 0)
```

**Comment by 23LuZ** [comment]
@pythonmobile Did you solve the problem?

**Comment by pythonmobile** [comment]
@23LuZ nope.

**Comment by nadimkaysar** [comment]
Did you solve this problem?
