### ISSUE TITLE
Error related to latest changes in repo

### ISSUE THREAD

**Issue by dimeldo** [bme-chatbots/dialogue-generation#4]
I didn't get this error before some changes done to the repo. Trying to run the model I get this:

```
Traceback (most recent call last):
  File "./src/train.py", line 519, in <module>
    main()
  File "./src/train.py", line 287, in main
    model, optimizer = amp.initialize(
NameError: name 'amp' is not defined
```

I couldn't figure out how to solve this.

**Comment by dimeldo** [comment]
Thanks!
