### ISSUE TITLE
Training is slow because apex is not recognized

### ISSUE THREAD

**Issue by dimeldo** [bme-chatbots/dialogue-generation#8]
Mixed precision is set to False because apex is not recognized as installed. Which make the training slow I think. I followed the commands in the README.

```
try:
    from apex import amp
    APEX_INSTALLED = True
    print("Yes")
except ImportError:
    APEX_INSTALLED = False
    print("No")

```
But still 'No' is getting printed here. Help debugging?

**Comment by dimeldo** [comment]
These commands seem to work ('Yes' is printed):

```
git clone --recursive https://github.com/NVIDIA/apex.git
cd apex && pip install .
```

Will follow if completely works.

**Comment by dimeldo** [comment]
Leading to this error:

```
-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/Downloads/GPT2/src/train.py", line 265, in main
    device=device)
  File "/Downloads/GPT2/src/model.py", line 71, in create_model
    args.model_name)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_utils.py", line 474, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_gpt2.py", line 578, in __init__
    self.transformer = GPT2Model(config)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_gpt2.py", line 451, in __init__
    self.h = nn.ModuleList([Block(config.n_ctx, config, scale=True) for _ in range(config.n_layer)])
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_gpt2.py", line 451, in <listcomp>
    self.h = nn.ModuleList([Block(config.n_ctx, config, scale=True) for _ in range(config.n_layer)])
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_gpt2.py", line 326, in __init__
    self.ln_1 = LayerNorm(nx, eps=config.layer_norm_epsilon)
  File "/usr/local/lib/python3.6/dist-packages/apex/normalization/fused_layer_norm.py", line 133, in __init__
    fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'

```

**Comment by Mrpatekful** [comment]
I have tested this on 2 machines and in google colab and it run without an error in every case. I think there is a problem with your apex installation. To reproduce my environment, follow these steps.

- use a virtualenv
```
pip install virtualenv

virutalenv venv
source venv/bin/activate
```

- install apex 

```
git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .
```

- clone the repo

```
cd ..
git clone https://github.com/bme-chatbots/dialogue-generation.git
cd dialogue-generation
pip install -r requirements.txt
python setup.py build_ext --inplace
python run.py
```

**Comment by dimeldo** [comment]
Trying to reproduce **exactly** your commands, everything seems to goes well, but when running the code I get this error:

```
terminate called after throwing an instance of 'c10::Error'
  what():  owning_ptr == NullType::singleton() || owning_ptr->refcount_.load() > 0 INTERNAL ASSERT FAILED at /pytorch/c10/util/intrusive_ptr.h:348, please report a bug to PyTorch. intrusive_ptr: Can only intrusive_ptr::reclaim() owning pointers that were created using intrusive_ptr::release(). (reclaim at /pytorch/c10/util/intrusive_ptr.h:348)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f02755cd273 in /home/ubuntu/venv/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x185ae8e (0x7f018db9ae8e in /home/ubuntu/venv/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #2: THStorage_free + 0x17 (0x7f018e31c1d7 in /home/ubuntu/venv/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x347bcd (0x7f027650ebcd in /home/ubuntu/venv/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: /home/ubuntu/venv/bin/python() [0x53dbec]
frame #5: /home/ubuntu/venv/bin/python() [0x5527d0]
frame #6: /home/ubuntu/venv/bin/python() [0x4c2098]
frame #7: /home/ubuntu/venv/bin/python() [0x56fa08]
frame #8: /home/ubuntu/venv/bin/python() [0x5b3567]
frame #9: /home/ubuntu/venv/bin/python() [0x5b3584]
frame #10: /home/ubuntu/venv/bin/python() [0x5b3584]
frame #11: /home/ubuntu/venv/bin/python() [0x5b3584]
frame #12: /home/ubuntu/venv/bin/python() [0x5b3584]
frame #13: /home/ubuntu/venv/bin/python() [0x5b3584]
frame #14: /home/ubuntu/venv/bin/python() [0x59d948]
frame #15: /home/ubuntu/venv/bin/python() [0x59d8ee]
frame #16: /home/ubuntu/venv/bin/python() [0x633073]
frame #17: _PyEval_EvalFrameDefault + 0x4648 (0x4fdaa8 in /home/ubuntu/venv/bin/python)
frame #18: /home/ubuntu/venv/bin/python() [0x4f7a28]
frame #19: /home/ubuntu/venv/bin/python() [0x4f876d]
frame #20: _PyEval_EvalFrameDefault + 0x467 (0x4f98c7 in /home/ubuntu/venv/bin/python)
frame #21: /home/ubuntu/venv/bin/python() [0x4f7a28]
frame #22: /home/ubuntu/venv/bin/python() [0x4f876d]
frame #23: _PyEval_EvalFrameDefault + 0x467 (0x4f98c7 in /home/ubuntu/venv/bin/python)
frame #24: /home/ubuntu/venv/bin/python() [0x4f6128]
frame #25: /home/ubuntu/venv/bin/python() [0x4f7d60]
frame #26: /home/ubuntu/venv/bin/python() [0x4f876d]
frame #27: _PyEval_EvalFrameDefault + 0x1260 (0x4fa6c0 in /home/ubuntu/venv/bin/python)
frame #28: /home/ubuntu/venv/bin/python() [0x4f6128]
frame #29: PyRun_StringFlags + 0xaf (0x64189f in /home/ubuntu/venv/bin/python)
frame #30: PyRun_SimpleStringFlags + 0x3d (0x64356d in /home/ubuntu/venv/bin/python)
frame #31: Py_Main + 0x35a (0x62b02a in /home/ubuntu/venv/bin/python)
frame #32: main + 0xe0 (0x4b4cb0 in /home/ubuntu/venv/bin/python)
frame #33: __libc_start_main + 0xe7 (0x7f027ae4fb97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #34: _start + 0x2a (0x5bdf6a in /home/ubuntu/venv/bin/python)

 70%|███████████████████████████████████████████████████▊                      | 1065372672/1520013706 [01:13<00:34, 13189950.80B/s]/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
100%|██████████████████████████████████████████████████████████████████████████| 1520013706/1520013706 [01:14<00:00, 20475968.99B/s]
 71%|████████████████████████████████████████████████████▍                     | 1077447680/1520013706 [01:14<00:33, 13199001.36B/s]/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
 71%|████████████████████████████████████████████████████▌                     | 1079233536/1520013706 [01:14<00:33, 13293889.78B/s]/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
 82%|████████████████████████████████████████████████████████████▉             | 1251241984/1520013706 [01:29<00:23, 11244307.51B/s]/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
Traceback (most recent call last):
  File "run.py", line 88, in <module>
    main()
  File "run.py", line 78, in main
    spawn(train, args=(args, ), nprocs=nprocs)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/ubuntu/venv/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/ubuntu/Downloads/dialogue-generation/src/train.py", line 266, in main
    device=device)
  File "/home/ubuntu/Downloads/dialogue-generation/src/model.py", line 71, in create_model
    args.model_name)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/pytorch_transformers/modeling_utils.py", line 477, in from_pretrained
    state_dict = torch.load(resolved_archive_file, map_location='cpu')
  File "/home/ubuntu/venv/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/torch/serialization.py", line 580, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 161434106 more bytes. The file might be corrupted.
```

These are all the commands I used after running the p3dn.24xlarge instance:

```
sudo killall apt apt-get
sudo dpkg --configure -a
sudo apt-get install python3-dev
sudo apt-get install virtualenv python
virtualenv --system-site-packages -p python3 venv
source venv/bin/activate

cd Downloads
git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .

cd ../
git clone https://github.com/bme-chatbots/dialogue-generation.git
cd dialogue-generation
pip install -r requirements.txt
python setup.py build_ext --inplace
python run.py --model_name gpt2-medium
```

**Comment by Mrpatekful** [comment]
Regarding that error the problem is in the distributed version only. As a quick fix you can first start the training on a single gpu instance and after the model is downloaded stop the training and switch to distributed version. I will push a fix in a few hours.

**Comment by dimeldo** [comment]
Ok, so I'm finally able to install apex and everything correctly (using nvidia provided image `docker pull nvcr.io/nvidia/tensorflow:19.02-py3`). But I'm getting an error. Here's the full trace:

```
Selected optimization level O2:  FP16 training with FP32 batchnorm and FP32 master weights.

Defaults for this optimization level are:
opt_level              : O2
loss_scale             : dynamic
master_weights         : True
cast_model_type        : torch.float16
keep_batchnorm_fp32    : True
enabled                : True
patch_torch_functions  : False
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
opt_level              : O2
loss_scale             : dynamic
master_weights         : True
cast_model_type        : torch.float16
keep_batchnorm_fp32    : True
enabled                : True
patch_torch_functions  : False
2019-08-26 15:45:38,947 - INFO - {'max_len': 100, 'data_dir': '/Downloads/dialogue-generation/src/../data', 'model_dir': '/Downloads/dialogue-generation/src/../model', 'batch_size': 64, 'learning_rate': 0.0001, 'cuda': True, 'grad_accum_steps': 2, 'model_name': 'gpt2-medium', 'top_k': 100, 'data_name': 'dailydialog', 'num_devices': 8, 'download_dir': '/Downloads/dialogue-generation/src/../data', 'mixed': True, 'eval_every_step': 3000, 'patience': 5, 'mode': 'train', 'top_p': 0.9, 'master_port': '29500', 'master_addr': '127.0.0.1', 'method': 'nucleus', 'max_epochs': 15, 'file_size': 100000, 'max_hist': 4, 'distributed': True}
Train 0:   0%|                                                                                              | 0/468 [00:00<?, ?it/s]/usr/local/lib/python3.5/dist-packages/torch/distributed/distributed_c10d.py:100: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/usr/local/lib/python3.5/dist-packages/torch/distributed/distributed_c10d.py:100: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
Train 0:   0%|                                                                                              | 0/468 [00:06<?, ?it/s]
/usr/local/lib/python3.5/dist-packages/torch/distributed/distributed_c10d.py:100: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/usr/local/lib/python3.5/dist-packages/torch/distributed/distributed_c10d.py:100: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/usr/local/lib/python3.5/dist-packages/torch/distributed/distributed_c10d.py:100: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/usr/local/lib/python3.5/dist-packages/torch/distributed/distributed_c10d.py:100: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/usr/local/lib/python3.5/dist-packages/torch/distributed/distributed_c10d.py:100: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/usr/local/lib/python3.5/dist-packages/torch/distributed/distributed_c10d.py:100: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
Traceback (most recent call last):
  File "run.py", line 92, in <module>
    main()
  File "run.py", line 82, in main
    spawn(train, args=(args, ), nprocs=nprocs)
  File "/usr/local/lib/python3.5/dist-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/usr/local/lib/python3.5/dist-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 7 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/Downloads/dialogue-generation/src/train.py", line 471, in main
    loss, acc = train_step(batch)
  File "/Downloads/dialogue-generation/src/train.py", line 351, in train_step
    loss, accuracy = forward_step(batch)
  File "/Downloads/dialogue-generation/src/train.py", line 341, in forward_step
    accuracy = reduce_tensor(accuracy)
  File "/Downloads/dialogue-generation/src/train.py", line 315, in reduce_tensor
    reduced /= args.world_size
AttributeError: 'Namespace' object has no attribute 'world_size'
```

**Comment by dimeldo** [comment]
Thanks!
